//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace BusinessSystemsApp.LoggerServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="LoggerServiceReference.Logger")]
    public interface Logger {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:Logger/LoggException", ReplyAction="urn:Logger/LoggExceptionResponse")]
        System.IAsyncResult BeginLoggException(string _browserInfo, string _exception, string _user, System.AsyncCallback callback, object asyncState);
        
        bool EndLoggException(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoggerChannel : BusinessSystemsApp.LoggerServiceReference.Logger, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoggExceptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoggExceptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoggerClient : System.ServiceModel.ClientBase<BusinessSystemsApp.LoggerServiceReference.Logger>, BusinessSystemsApp.LoggerServiceReference.Logger {
        
        private BeginOperationDelegate onBeginLoggExceptionDelegate;
        
        private EndOperationDelegate onEndLoggExceptionDelegate;
        
        private System.Threading.SendOrPostCallback onLoggExceptionCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public LoggerClient() {
        }
        
        public LoggerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoggerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoggerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoggerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<LoggExceptionCompletedEventArgs> LoggExceptionCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult BusinessSystemsApp.LoggerServiceReference.Logger.BeginLoggException(string _browserInfo, string _exception, string _user, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLoggException(_browserInfo, _exception, _user, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool BusinessSystemsApp.LoggerServiceReference.Logger.EndLoggException(System.IAsyncResult result) {
            return base.Channel.EndLoggException(result);
        }
        
        private System.IAsyncResult OnBeginLoggException(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string _browserInfo = ((string)(inValues[0]));
            string _exception = ((string)(inValues[1]));
            string _user = ((string)(inValues[2]));
            return ((BusinessSystemsApp.LoggerServiceReference.Logger)(this)).BeginLoggException(_browserInfo, _exception, _user, callback, asyncState);
        }
        
        private object[] OnEndLoggException(System.IAsyncResult result) {
            bool retVal = ((BusinessSystemsApp.LoggerServiceReference.Logger)(this)).EndLoggException(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoggExceptionCompleted(object state) {
            if ((this.LoggExceptionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoggExceptionCompleted(this, new LoggExceptionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoggExceptionAsync(string _browserInfo, string _exception, string _user) {
            this.LoggExceptionAsync(_browserInfo, _exception, _user, null);
        }
        
        public void LoggExceptionAsync(string _browserInfo, string _exception, string _user, object userState) {
            if ((this.onBeginLoggExceptionDelegate == null)) {
                this.onBeginLoggExceptionDelegate = new BeginOperationDelegate(this.OnBeginLoggException);
            }
            if ((this.onEndLoggExceptionDelegate == null)) {
                this.onEndLoggExceptionDelegate = new EndOperationDelegate(this.OnEndLoggException);
            }
            if ((this.onLoggExceptionCompletedDelegate == null)) {
                this.onLoggExceptionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoggExceptionCompleted);
            }
            base.InvokeAsync(this.onBeginLoggExceptionDelegate, new object[] {
                        _browserInfo,
                        _exception,
                        _user}, this.onEndLoggExceptionDelegate, this.onLoggExceptionCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override BusinessSystemsApp.LoggerServiceReference.Logger CreateChannel() {
            return new LoggerClientChannel(this);
        }
        
        private class LoggerClientChannel : ChannelBase<BusinessSystemsApp.LoggerServiceReference.Logger>, BusinessSystemsApp.LoggerServiceReference.Logger {
            
            public LoggerClientChannel(System.ServiceModel.ClientBase<BusinessSystemsApp.LoggerServiceReference.Logger> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginLoggException(string _browserInfo, string _exception, string _user, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = _browserInfo;
                _args[1] = _exception;
                _args[2] = _user;
                System.IAsyncResult _result = base.BeginInvoke("LoggException", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndLoggException(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("LoggException", _args, result)));
                return _result;
            }
        }
    }
}
