//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace BusinessSystemsApp.ConfigurationServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ConfigurationServiceReference.Configuration")]
    public interface Configuration {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:Configuration/GetAppSettingsValue", ReplyAction="urn:Configuration/GetAppSettingsValueResponse")]
        System.IAsyncResult BeginGetAppSettingsValue(string name, System.AsyncCallback callback, object asyncState);
        
        string EndGetAppSettingsValue(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConfigurationChannel : BusinessSystemsApp.ConfigurationServiceReference.Configuration, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAppSettingsValueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAppSettingsValueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConfigurationClient : System.ServiceModel.ClientBase<BusinessSystemsApp.ConfigurationServiceReference.Configuration>, BusinessSystemsApp.ConfigurationServiceReference.Configuration {
        
        private BeginOperationDelegate onBeginGetAppSettingsValueDelegate;
        
        private EndOperationDelegate onEndGetAppSettingsValueDelegate;
        
        private System.Threading.SendOrPostCallback onGetAppSettingsValueCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ConfigurationClient() {
        }
        
        public ConfigurationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConfigurationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigurationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigurationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetAppSettingsValueCompletedEventArgs> GetAppSettingsValueCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult BusinessSystemsApp.ConfigurationServiceReference.Configuration.BeginGetAppSettingsValue(string name, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAppSettingsValue(name, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string BusinessSystemsApp.ConfigurationServiceReference.Configuration.EndGetAppSettingsValue(System.IAsyncResult result) {
            return base.Channel.EndGetAppSettingsValue(result);
        }
        
        private System.IAsyncResult OnBeginGetAppSettingsValue(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string name = ((string)(inValues[0]));
            return ((BusinessSystemsApp.ConfigurationServiceReference.Configuration)(this)).BeginGetAppSettingsValue(name, callback, asyncState);
        }
        
        private object[] OnEndGetAppSettingsValue(System.IAsyncResult result) {
            string retVal = ((BusinessSystemsApp.ConfigurationServiceReference.Configuration)(this)).EndGetAppSettingsValue(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAppSettingsValueCompleted(object state) {
            if ((this.GetAppSettingsValueCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAppSettingsValueCompleted(this, new GetAppSettingsValueCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAppSettingsValueAsync(string name) {
            this.GetAppSettingsValueAsync(name, null);
        }
        
        public void GetAppSettingsValueAsync(string name, object userState) {
            if ((this.onBeginGetAppSettingsValueDelegate == null)) {
                this.onBeginGetAppSettingsValueDelegate = new BeginOperationDelegate(this.OnBeginGetAppSettingsValue);
            }
            if ((this.onEndGetAppSettingsValueDelegate == null)) {
                this.onEndGetAppSettingsValueDelegate = new EndOperationDelegate(this.OnEndGetAppSettingsValue);
            }
            if ((this.onGetAppSettingsValueCompletedDelegate == null)) {
                this.onGetAppSettingsValueCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAppSettingsValueCompleted);
            }
            base.InvokeAsync(this.onBeginGetAppSettingsValueDelegate, new object[] {
                        name}, this.onEndGetAppSettingsValueDelegate, this.onGetAppSettingsValueCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override BusinessSystemsApp.ConfigurationServiceReference.Configuration CreateChannel() {
            return new ConfigurationClientChannel(this);
        }
        
        private class ConfigurationClientChannel : ChannelBase<BusinessSystemsApp.ConfigurationServiceReference.Configuration>, BusinessSystemsApp.ConfigurationServiceReference.Configuration {
            
            public ConfigurationClientChannel(System.ServiceModel.ClientBase<BusinessSystemsApp.ConfigurationServiceReference.Configuration> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetAppSettingsValue(string name, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = name;
                System.IAsyncResult _result = base.BeginInvoke("GetAppSettingsValue", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetAppSettingsValue(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetAppSettingsValue", _args, result)));
                return _result;
            }
        }
    }
}
